# Generated by Django 4.2.4 on 2024-03-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Honda', 'Honda'), ('Nissan', 'Nissan'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Volkswagen', 'Volkswagen'), ('Audi', 'Audi'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Lexus', 'Lexus'), ('Subaru', 'Subaru'), ('Mazda', 'Mazda'), ('Dodge', 'Dodge'), ('Porsche', 'Porsche'), ('Jeep', 'Jeep'), ('Cadillac', 'Cadillac'), ('Tesla', 'Tesla'), ('Volvo', 'Volvo'), ('Land Rover', 'Land Rover'), ('Jaguar', 'Jaguar'), ('Acura', 'Acura'), ('Infiniti', 'Infiniti'), ('Mini', 'Mini'), ('Buick', 'Buick'), ('Mitsubishi', 'Mitsubishi'), ('Chrysler', 'Chrysler'), ('Fiat', 'Fiat'), ('Alfa Romeo', 'Alfa Romeo'), ('Bentley', 'Bentley'), ('Aston Martin', 'Aston Martin'), ('Lamborghini', 'Lamborghini'), ('Ferrari', 'Ferrari'), ('Maserati', 'Maserati'), ('Rolls-Royce', 'Rolls-Royce'), ('McLaren', 'McLaren'), ('Pagani', 'Pagani'), ('Bugatti', 'Bugatti')], max_length=50),
        ),
    ]
